### ISSUE TITLE
Address vacuum steps in the proposed TVSA cycle

### ISSUE THREAD

**Issue by taehunk333** [taehunk333/toPSAil#12]
**Issue**: Currently, step 2 through 6 in the TVSA cycle should pull vacuum down stream. However, as seen in https://github.com/taehunk333/toPSAil/issues/5#issuecomment-2509028768, the vacuum steps not working correctly.

**Desired**: Correctly implement the vacuum steps.

**Comment by vajcsi** [comment]
I could make my previous purge-testing case reach vacuum and extend on it but could not make the existing TVSA case work the same way. So I built up the new one to resemble the TVSA cycle and now it works. It is probably a settings difference that I did not find, but maybe it's best to build on the new TVSA2 case that works properly and remove the original one.

![colPresProfile](https://github.com/user-attachments/assets/b9a560df-1dc4-4924-96d8-e1189b3f1478)
